### ISSUE TITLE
No temperature on Ryzen 7 2700x

### ISSUE THREAD

**Issue by Simion1z1** [koogar/HardwareSerialMonitor#1]
I compiled the source code but I don't receive the temperature on my Amd R7 2700x processor. I tried this software on another pc with Amd Phenom II X4 955 and with that cpu, temperature is working properly.
![image](https://user-images.githubusercontent.com/52258451/106817855-1fc84e00-6680-11eb-959a-89c2b66e2efa.png)

**Comment by koogar** [comment]
Are you just running the debug? no arduino?
HardwareSerialMonitor has to be run as admin even in debug in VS or it wont read the sensors

**Comment by Simion1z1** [comment]
Solved. I used it directly on VS which does not compile open the as administrator. After I opened from bin folder as Administrator, was working well. Thanks!

**Comment by wh1ter0z** [comment]
Hello 

I have rx5700xt all.things are working fine 

But gpu power , gpu shader , gpu fan speed , gpu vram , gpu used , gpu total are has no information

**Comment by Simion1z1** [comment]
> Hello
> 
> I have rx5700xt all.things are working fine
> 
> But gpu power , gpu shader , gpu fan speed , gpu vram , gpu used , gpu total are has no information

Open it as administrator

**Comment by wh1ter0z** [comment]
> > Hello
> > I have rx5700xt all.things are working fine
> > But gpu power , gpu shader , gpu fan speed , gpu vram , gpu used , gpu total are has no information
> 
> Open it as administrator

Not work ... full admin permission

**Comment by koogar** [comment]
you could try this 
https://github.com/koogar/Wee-Hardware-Stat-Server
