### ISSUE TITLE
BT is working but USB Serial not

### ISSUE THREAD

**Issue by iberotecno** [koogar/HardwareSerialMonitor#2]
Hello. First of all congratulations for your incredible work. Is awesome! I'm using Wemos LOLIN32 and all works well via BT. But for some reason, I can not get connection via serial, only blank screen after startup logos. In automatic mode, the tray icon of HW Serial Monitor is green. If I manual selecting the port, shows gray. But still blank screen in both cases. I tryed to restart computer, change baudarate of the virtual com port in device manager... and nothing works. I'm choosing "#define enable_DualSerialEvent" in config.h Any help please? Thank you!

**Comment by iberotecno** [comment]
Where is the .exe of the v1.4? I can not find it

**Comment by koogar** [comment]
Hi,

Yes there is an issue with serial. 

I had it working initially but after some other changes it seems only BT works presently.
I  have not had the time to weed the problem out.

V1.4 is under the 1.3d release tab the only difference is the baud rate

https://github.com/koogar/HardwareSerialMonitor/releases/tag/v1.3d
