### ISSUE TITLE
Incorrect CPU temperature

### ISSUE THREAD

**Issue by beyondthemind91an** [koogar/HardwareSerialMonitor#4]
Hello! Thank you for this awesome software! However, I have a problem with it sending the correct CPU temperature. I can't actually find the same temperature in any other software lika OpenHardwareMonitor or HWMonitor. It is averaging 10 degrees C to high, and doesn't really follow the CPU temperature either.

**Comment by koogar** [comment]
Hey,
Are you on a Ryzen by any chance?

**Comment by beyondthemind91an** [comment]
Sorry, I forgot to mention what components I have. I run a Intel 10600kf on a MSI z490-a pro motherboard.

**Comment by koogar** [comment]
Hi,
 Its a bit hard for me to test obviously, as i do not have the same hardware. 
 I imagine openhardwaremonitor is maybe using an offset in the windows software to correct this.
 I am just taking the data straight from the openhardwaremonitor  .DLL
 I might include an option for offset in a future release.

if you run this https://github.com/koogar/HardwareSerialMonitor/tree/main/Libre/WeeStatServer-0.5_0.9.1
do you get the same results?

you will have to edit the appsettings.json file in notepad. Change the com port at the bottom section of the page to match the port you are using. 

Then run the WeeHardwareStatServer.exe  as ADMIN

**Comment by beyondthemind91an** [comment]
Thank you for taking your time! I have edited the json-file to the correct COM-port, however the program does not run. Also tried changing the BAUD-rate.

The strange thing is that when i stress the CPU, then it shows the correct temperature, but when in idle it doesn't. It is like it reads the temperature from a different sensor than the CPU, but that sensor is still somehow affected by the CPU temperature.

**Comment by beyondthemind91an** [comment]
Is it possible to change what sensor to read/send from?

**Comment by koogar** [comment]
Its not really possible to change the sensor without a lot of work in the source code.

"however the program does not run. Also tried changing the BAUD-rate"

Ah I should have mentioned you need .NET 5
https://dotnet.microsoft.com/en-us/download/dotnet/5.0

**Comment by beyondthemind91an** [comment]
Thank you so much! Running WeeStatServer gives a more accurate temperature of the CPU. Looking forward to the main release!

**Comment by koogar** [comment]
WeeStatServer is by Vinod Mishra. 
He made it to be compatiable with my phatstats/gnatstats code with some tweaks to the JSON file. 
It uses the LibreHardwareMonitor's .DLL :)
