### ISSUE TITLE
high cpu load by HardwareSerialMonitor.exe

### ISSUE THREAD

**Issue by KKuKK** [koogar/HardwareSerialMonitor#5]
Hallo

I have a win10 32 bit system.
I tried all versions I could find of the HardwareSerialMonitor.exe program and each causes high cpu load by this 3 
win10 programs:

-BackgroundTaskHost.exe
-RuntimeBroker.exe
-WmiPrvSE.exe

I tried all I could find to solve this problem, and I am sure the cause is the HardwareSerialMonitor.exe because the load 
goes down immediately when I exit it.

Is there any known issue? I am now running your version which I installed with HardwareSerialMonitor_9600bps_setup in the 
Experimental folder.
The cpu load is down to normal after some minutes. Would be great if it holds down.

It's hard to tell for sure, because every system is different, my one has some issues build up over time, so may be the reason is my 
system only.

Thanks for a hint and thanks for your program.

Greetings klaus

**Comment by koogar** [comment]
Sorry I have never experienced high load with hardwareSerialMonitor, it has also never been reported.
The program does not even register a percentage in processes.
Then again i have only ever run it on 64bit windows.

So you have tried the version from here? https://hackaday.io/project/19018-phat-stats-pc-performance-tft-display

**Comment by KKuKK** [comment]
Hi !
Thanks for your fast answer. The program HardwareSerialMonitor.exe is in the task manager listed as "GNAT STATS PC
performance monitor". This is not the program which caused the high cpu load.
The 3 windows services mentioned above were the one. Somehow the HardwareSerialMonitor.exe uses these services
or brings them to life. As soon as I stopped  HardwareSerialMonitor.exe then cpu load of these 3 services goes down
at once. 
I tried every version of HardwareSerialMonitor.exe which I could find. Now the one HardwareSerialMonitor_9600bps_setup in the Experimental folder is working. Don't know whether it works tomorrow. The other one works sometimes without 
causing high cpu load, but most of the time not. I could not figure it out why.

If I am the only one who has this problem, then I think it is related to my Win10 system.

I have tried the version you mentioned above. No change.

Thanks for your help so far. I know, if you have an other system, you cannot test it.
greeting klaus

**Comment by koogar** [comment]
I do not have any issue with those services when running HSM.
Did you set task scheduler to run HSM at windows startup?

**Comment by KKuKK** [comment]
Yes, but I stopped it. It makes no sense as long as the load rises to 90% when it’s running.I will give you an update tomorrow. Today  the experimental version runs the whole dayWithout any issues. Hope it will stay like This tomorrow. If so, then there must be a difference between the versions.Von meinem iPhone gesendetAm 16.03.2023 um 22:22 schrieb Tallman Labs ***@***.***>:﻿
I do not have any issue with those services when running HSM.
Did you set task scheduler to run HSM at windows startup?

**Comment by KKuKK** [comment]
Btw i read there was an issue with older versions of the Windows WMI service.Something with handling the requests.I have the win10 version 1702 running,Because the 19er version where very slow.Microsoft addressed these issues in later Versions, so may be my one is a bug.It’s obviously unique with my system, so youCan’t do anything about it.Thanks for your help Von meinem iPhone gesendetAm 16.03.2023 um 22:33 schrieb Klaus Kreutzer ***@***.***>:﻿Yes, but I stopped it. It makes no sense as long as the load rises to 90% when it’s running.I will give you an update tomorrow. Today  the experimental version runs the whole dayWithout any issues. Hope it will stay like This tomorrow. If so, then there must be a difference between the versions.Von meinem iPhone gesendetAm 16.03.2023 um 22:22 schrieb Tallman Labs ***@***.***>:﻿
I do not have any issue with those services when running HSM.
Did you set task scheduler to run HSM at windows startup?

**Comment by koogar** [comment]
there is no diff between between versions the experimental folder has the same code just it wrapped up in an installer

**Comment by KKuKK** [comment]
Ok that’s crazy. May be the installation does Something.Von meinem iPhone gesendetAm 16.03.2023 um 22:44 schrieb Tallman Labs ***@***.***>:﻿
there is no diff between between versions the experimental folder has the same code just it wrapped up in an installer

**Comment by KKuKK** [comment]
Hi
and so it is, this morning the load is up again! No matter which version 
I try. As soon as I start HardwareSerialMonitor.exe, WmiPrvSE.exe needs
30-50% of CPU load. That’s crazy, yesterday it worked the whole day.
If I stop HardwareSerialMonitor.exe the load is immediately  0%. HardwareSerialMonitor.exe 
clearly causes the high cpu usage.
Greetings klaus

**Comment by koogar** [comment]
Hi Klaus,

I just  installed HSM on 3 different systems  Win7 64, Win10 64, Win11 64bit. 
1 of the laptops would be considered a potato PC by todays standards. 
None of them exibit high cpu load on HSM or WmiPrvSE.exe. 

I do not have a 32bit OS to test any further but I expect the same result. Maybe the high load is related to your windows install and a driver related to the COM port service.

Out of interest have you tried it on a different PC? , what are the specs of your PC and what arduino hardware are you using?

**Comment by KKuKK** [comment]
Hi 

First thanks for your help. it really drives me nuts, I build a nice STM32F103 with Nokia5110 
display to see the hardware load, nice add on, nice to know. And now it is quite useless.

I cannot run it with this high cpu load.

I don’t think it is related to my usb driver, there is no change at all, and the whole day 
yesterday it worked without any noticeable cpu load. But only after installing the experimental
version. I will try it on a different com port. Its a good idea.

I will try it on a 64bit win10 system and another 32bit win10 system, both with
all win10 updates up to date.

I do not understand how it can work a whole day and the next day, obviously after a
new start, the problem is there again.

greetings klaus

**Comment by KKuKK** [comment]
quick update 

I run this commands as root.

sfc /scannow
Dism /Online /Cleanup-Image /CheckHealth
Dism /Online /Cleanup-Image /ScanHealth
DISM.exe /Online /Cleanup-image /Restorehealth

I installed the experimetal version again. Then two win10
programs starts realy hard.

-runtimebroker
-cortana  something, its gone, don’t now exactly the name

now it works again without any cpu load, it is exactly 0%
that’s insane! And you are right, it does not matter which 
version I use, they are the same.

can’t run every day all that stuff 

this is wired. I am really curious now.  

greetings klaus

**Comment by KKuKK** [comment]
I don't think it is a com port triber issue, if so, the load of the HardwareSerialMonitor.exe should go up.
it's a problem with the communication between the HMI Host and HardwareSerialMonitor.exe.
I tried OpenHardwareMonitor and as I understand, the OpenHardwareMonitorLib.dll is used by HSM.exe
OpenHardwareMonitor.exe runs without problems.

I will check the other systems tomorrow.

**Comment by KKuKK** [comment]
hi
I checked it now on 2 win10 systems with all updates. 64bit and 32bit
There is no issue, 0% cpu load. 
Its my older win10 version with a bug! Crazy.
So all for nothing, sorry, I had to check it first.
greetings Klaus

**Comment by KKuKK** [comment]
Hi 
just for info, I copied my system on a ssd, made a whole updated and 
nothing changed. High cpu load after running HSM 
That sucks. 
greetings

**Comment by KKuKK** [comment]
Hi 
Final comment, you were absolutly right at the beginning.

You nailed the problem, it was the usb port. 
I finally desided to update my 1703 version to the latest, took a lot of 
time.
All errors of the system are repaired, but the problem was still there!
50% cpu load when running HSM.

I use all usb ports of my notebook, 7 atmega and stm chips are running.

So I need usb hubs. It don’t work on a hub, it only works directly on 
an usb port of the notebook.
That’s the reason why it worked on my other NB, I connected it to the 
usb directly.

Strange.
Thank’s for your help.
greetings klaus

**Comment by KKuKK** [comment]
Morning

may be you are interested, because it is still not working. 
I have the newest Win10, no issues any more. I use 
the monitor direct at the usb port of the notebook. 

It works yesterday, today it starts all over again, high cpu load 
50% and more for HSM.

I put the HSM in the startupfolder, this don’t work.
I think it is a com port issue. because if I open HSM in
the taskbar, the program scans all ports and I cannot 
select any item. There is a working icon for the mouse 
and it never stops.

It connects to the former port, shows the cpu load in my 
monitor, but the cpu load is very high. I cannot even exit 
the menu. I think it cannot finish the searching algorithm.

There is obviously a porblem with the scanning of the com ports.
As I wrote, I have 7 different atmel chips running. May be this 
is a problem.


greeting klaus

**Comment by KKuKK** [comment]
Morning!

Finally I think I can nail the error. It has to do with the com Ports, 
but nothing with an usb hub, or where I connect the usb to the notebook 

If I start the notebook with the usb2ttl converter plugged in and 
the HSM tries to connect automatically, it don’t work without extreme
high cpu load of WmiPrvSE.exe.

If I try to select the port manually, the menu don’t react to the mouse.
I cannot do anything. I have to kill the process.

But, if I disconnect the usb2ttl chip, its a ps2303, then reconnect it 
to the notebook after starting HSM,  I can manually select the com port and it works
without high cpu load of WmiPrvSE.exe.

Clearly I must run HSM before the ps2303 is plugged in, the automatic 
connection is not working for me.

Don’t know what causes this behavior.

greetings klaus

**Comment by KKuKK** [comment]
Hi
last question, nothing works, only sometimes after 100 clicks and kills.
It is the automatic connection that don’t work, no matter what I try.

Is there a way to prevent the automatic connection?

I cannot uncheck the option in the menu, because I cannot
do anything in the menu. If I open it up, it nearly never gets ready to
click anything. It is stuck.

Is there a config file or a registry entry for the last port in win10?
I checked all files in the folder, but there was nothing obvious.

Somewhere  the last port must be stored. I use 10 ports and the HSM
automatically connects to port 12, the first port I used for HSM.

If I run HSM, it connects to the right port and the display starts 
plotting with high cpu. As soon as I am able to click on port 12
in the menu, the high cpu load stops at once.

The problem is, I cannot not click on then port in the menu,
it is not reacting, at least 99% of the time. 

After I was able to click on the port in the menu, I can disconnect and
connect to the port as much as I want, the cpu load stays low and 
connects automatically. 

All the mess starts again after reboot.

Thanks for your help
greetings klaus

**Comment by koogar** [comment]
Hi,

The term automatic refers to connecting to the last recorded port it could be anything in the list. It does not auto detect anything.

The only time I have had HSM lag is when using Bluetooth serial ports and you select the wrong one.
When you use Bluetooth classic you get 2 windows com ports one for send and one for receive. Neither is labelled as such. So you can sometime select the incorrect port (the receive  port) and it lags HSM due to it hitting a dead end on the polling.

Have you tried going to device manager and selected “show hidden devices) and deleted/uninstall all the com ports.

It sound like you may have some sort of rogue com port

**Comment by KKuKK** [comment]
Thanks for your helpYes, my com ports are really a mess.But these port handling by windows is a mess on it’s own. If I have to change the com ports for my devices for arrangement reasons Then I have to manually set the com port numbers. Even the old driver were replaced by new ones, which don’t work.To make it clear, I don’t choose the wrong port the first time. The next day in the menuthis port is selected without any action from me and my monitor starts plotting. But the cpu load is unbearable high.If I am able to select this same port in the menu manually, then the CPU load goes Immediately to 0%. This makes me thinkThe automatic connection process is faulty On my system. The searching for com ports Seems to never stop. Therefore I am 99% of the time not able to click on any item in the menu. To be honest, I have now idea how these task of listing and connecting to the last port can cause such a huge cpu load.How can HSM connect the next day to the selected port from the day before?Where is the com port number stored? In my device manager are only the ports listed which I use. I don’t use Bluetooth.But if I connect a usb2ttl chip to another Com port and manually set the old com number, there are a lot more ports listed asused. A complete reset of these port list Is a good idea. If there are lost ports listed It could be the reason why the search process never stops.To be more exact, I think the search process Stops, otherwise the menu would not show the help and exit item. But after that is something hanging.I will try what you suggest.My other solution is to deselect the automatic connection. Would be annoying Every day, but better than nothing. I don’t see how to prevent this.Greetings klausVon meinem iPhone gesendetAm 06.04.2023 um 14:19 schrieb Tallman Labs ***@***.***>:﻿
Hi,
The term automatic refers to connecting to the last recorded port it could be anything in the list. It does not auto detect anything.
The only time I have had HSM lag is when using Bluetooth serial ports and you select the wrong one.
When you use Bluetooth classic you get 2 windows com ports one for send and one for receive. Neither is labelled as such. So you can sometime select the incorrect port (the receive  port) and it lags HSM due to it hitting a dead end on the polling.
Have you tried going to device manager and selected “show hidden devices) and deleted/uninstall all the com ports.
It sound like you may have some sort of rogue com port

**Comment by KKuKK** [comment]
HiChecked it right now for hidden devices.What a mess. Double, triple and more devices on the same com port.Cleared all. Hope this helps. Right now itWorks with low cpu load, before the cleaning. If this is the case it stays like this until reboot.I am still interested where the last used port is stored in HSMGreetings klausVon meinem iPhone gesendetAm 06.04.2023 um 14:19 schrieb Tallman Labs ***@***.***>:﻿
Hi,
The term automatic refers to connecting to the last recorded port it could be anything in the list. It does not auto detect anything.
The only time I have had HSM lag is when using Bluetooth serial ports and you select the wrong one.
When you use Bluetooth classic you get 2 windows com ports one for send and one for receive. Neither is labelled as such. So you can sometime select the incorrect port (the receive  port) and it lags HSM due to it hitting a dead end on the polling.
Have you tried going to device manager and selected “show hidden devices) and deleted/uninstall all the com ports.
It sound like you may have some sort of rogue com port

**Comment by KKuKK** [comment]
Hi 

A short update, it all has no effect. Still not working, I cleared
all unused ports, but no change. As long as I am unable to 
click manually on the com port where the monitor is located,
the cpu load is 50%.

The menu is busy and I am not able to click on anything.

There is a workaround, if I start HSM with the monitor connected,
HSM tries to connect to the port and starts sending data. CPU load 
is very high. 

Now I disconnect the monitor, the cpu load goes to 0%, I reconnect
the monitor and now I am most of the time able to click on the port
in the menu. This port is aleady selected, but only if I click on the
menu item, then the cpu load goes to 0%.

That’s crazy.

Just for info.

greetings Klaus
