### ISSUE TITLE
Cannot remember BT device COM

### ISSUE THREAD

**Issue by aria4castm** [koogar/HardwareSerialMonitor#6]
Greetings,
I am using v1.4.2 version, 9600 baud rate of the monitor at present in my Win10.22H2 PC. I have to select my BT COM when I start the serial monitor (starts in red icon). The USB serial port can be properly remembered by automatic mode (starts in green icon).  

I tried to alter the config.ini file, but all BT COMs are the same in the file, showing:

;This is the configuration file for the Application
[DeviceConfig]
VendorID = BTHE
ProductID = BTHE
DeviceID = BTHENUM\{00001101-0000-1000-8000-00805F9B34FB}
isBT = false
BTDevice = 

My experience could be greatly improved if this issue can be dealt with. Thank you for your project anyway.

**Comment by koogar** [comment]
unfortunatly BT will not be remembered there is not much i can do about it.
